### ISSUE TITLE
The full code of model.py

### ISSUE THREAD

**Issue by JingliSHI0206** [chenshaowei57/BMRC#4]
After reading the paper, i find that the function Softmax does not appear in model.py. may i know if the file list full code? thanks.

**Comment by chenshaowei57** [comment]
Softmax functions are written in main.py.

**Comment by JingliSHI0206** [comment]
> Softmax functions are written in main.py.

oh. i skip the main.py. my bad. thank you so much for your reply. will spend more time to read the paper and code. thank you again for sharing the code.
