### ISSUE TITLE
请问代码中的 query_mask 和 query_seg 具体是什么 有什么作用

### ISSUE THREAD

**Issue by bylcodebad** [chenshaowei57/BMRC#6]
请问代码中的 query_mask 和 query_seg 具体是什么 有什么作用

**Comment by chenshaowei57** [comment]
mask和seg是bert的输入，mask用于区别输入序列和padding，seg用于区别每个输入序列中哪些词属于query，哪些是原始句子。

**Comment by bylcodebad** [comment]
> mask和seg是bert的输入，mask用于区别输入序列和padding，seg用于区别每个输入序列中哪些词属于query，哪些是原始句子。

明白了，感谢！
