### ISSUE TITLE
您好，代码中的passenge 代表着什么呢

### ISSUE THREAD

**Issue by bylcodebad** [chenshaowei57/BMRC#8]
您好，代码中的passenge 代表着什么呢
passenge = batch_dict['forward_asp_query'][0][passenge_index].squeeze(1)

**Comment by chenshaowei57** [comment]
passenge就是代表样本原始句子对应的词。因为forward_asp_query是query和原始句子拼接得到的，passenge就是把其中的原始句子分离出来，用于第二轮、第三轮输入序列的构造。

**Comment by bylcodebad** [comment]
> passenge就是代表样本原始句子对应的词。因为forward_asp_query是query和原始句子拼接得到的，passenge就是把其中的原始句子分离出来，用于第二轮、第三轮输入序列的构造。

明白了，感谢！
